/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ch450.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
  final Board<Character> theBoard;
  final BoardTextView view;
  final BufferedReader inputReader;
  final PrintStream out;

  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;
  }

  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  public void doOnePlacement() throws IOException {
    String prompt = "Where would you like to put your ship?";
    Placement p1 = readPlacement(prompt);
    Coordinate coordi = p1.getWhere();
    final AbstractShipFactory<Character> shipFactory;
    shipFactory = new V1ShipFactory();
    Ship<Character> s = shipFactory.makeDestroyer(p1);
    theBoard.tryAddShip(s);
    out.println(view.displayMyOwnBoard());

  }

  public static void main(String[] args) throws IOException {
    Board<Character> b1 = new BattleShipBoard<Character>(10, 20);
    InputStreamReader r = new InputStreamReader(System.in);
    PrintStream out = System.out;
    App app = new App(b1, r, out);
    app.doOnePlacement();

  }
}
